---
Title: "Data Exploration"
Author: "Gavin Cassidy
format: html
---


```{r}
library(tidyverse)
library(readr)
library(here)
```



```{r}
skaters <- read.csv(here("data/skaters.csv"))

skaters |> filter(start_year == min(start_year))
```

```{r}
siblings <- read.csv(here("data/siblings.csv"))

siblings_full <- siblings |> pivot_longer(cols = c(sib1, sib2, sib3, sib4, sib5, sib6), names_to = "sib", values_to = "sibling", values_drop_na = TRUE)
```

```{r}
parents <- read.csv(here("data/parent.csv"))
```



```{r}
skaters_wsib <- left_join(skaters, siblings_full, by = join_by(player == sibling))
```



```{r}
has_sib <- skaters_wsib |> filter(!is.na(id))
no_sib <- skaters_wsib |> filter(is.na(id))
```

## Plot 1
```{r}
g_a_sib <- has_sib |> group_by(family, id) |> summarise(tot_G = sum(G), tot_A = sum(A))

top_ten <- has_sib |> group_by(id, family) |> summarise(tot_G = sum(G), tot_A = sum(A)) |> arrange(desc(tot_A)) |> ungroup() |> slice(1:10)

ggplot(data = g_a_sib, aes(x = tot_G, y = tot_A)) +
    geom_point(aes(color = tot_G)) +
    geom_label(data = top_ten, aes(label = family)) +
    scale_color_viridis_c()
```


```{r}
gretzky <- skaters_wsib |> filter(family == "Gretzky") |> mutate(tot_G = G, tot_A = A, tot_GP = GP, tot_PIM = PIM)
sutter <- skaters_wsib |> filter(family == "Sutter") |> mutate(tot_G = G, tot_A = A, tot_GP = GP, tot_PIM = PIM)

ggplot(data = g_a_sib, aes(x = tot_G, y = tot_A)) +
    geom_point(aes(color = tot_G)) +
    geom_label(data = gretzky, aes(label = player)) +
    geom_label(data = sutter, aes(label = player)) +
    scale_color_viridis_c()
```


```{r}
arranged_skaters <- skaters_wsib |> filter(start_year <= 2000 & end_year >= 1980 & id >= 0) |> arrange(desc(PTS)) |> mutate(player = fct_reorder(player, PTS))

ggplot(data = arranged_skaters, aes(x = player, y = PTS)) +
    geom_col() +
    geom_label(data = gretzky, aes(label = player)) +
    coord_flip()
```


```{r}
pim_sib <- has_sib |> group_by(id, family) |> summarise(tot_PIM = sum(PIM), tot_GP = sum(GP)) 

top_pim <- has_sib |> group_by(family) |> summarise(tot_PIM = sum(PIM), tot_GP = sum(GP)) |> arrange(desc(tot_PIM)) |> slice(1:10)

ggplot(data = pim_sib, aes(x = tot_GP, y = tot_PIM)) +
    geom_point(aes(color = tot_PIM)) +
    geom_label(data = top_pim, aes(label = family)) +
    scale_color_viridis_c()
```


```{r}
hunter <- skaters_wsib |> filter(family == "Hunter") |> mutate(tot_GP = GP, tot_PIM = PIM)

ggplot(data = pim_sib, aes(x = tot_GP, y = tot_PIM)) +
    geom_point(aes(color = tot_PIM)) +
    geom_label(data = hunter, aes(label = player)) +
    geom_label(data = sutter, aes(label = player)) +
    geom_label(data = gretzky, aes(label = player)) +
    scale_color_viridis_c()

```


```{r}
skaters_wsib |> mutate(sib_ind = if_else(!is.na(id), 1, 0)) |>
    group_by(sib_ind) |> summarise(size = n())

## no sib 7276
## sib 622
```

```{r}
skaters_wsib |> mutate(sib_ind = if_else(!is.na(id), 1, 0)) |>
    group_by(sib_ind) |> summarise(tot_g = sum(G), g_per_player = sum(G)/n())
```

```{r}
skaters_wsib |> mutate(sib_ind = if_else(!is.na(id), 1, 0)) |>
    group_by(sib_ind) |> summarise(tot_a = sum(A), a_per_player = sum(A)/n())
```



```{r}
skaters_wsib |> mutate(sib_ind = if_else(!is.na(id), 1, 0)) |>
    group_by(sib_ind) |> summarise(tot_pts = sum(PTS), pts_per_player = sum(PTS)/n())
```


```{r}
skaters_wsib |> mutate(sib_ind = if_else(!is.na(id), 1, 0)) |>
    group_by(sib_ind) |> filter(!is.na(PIM)) |> summarise(tot_PIM = sum(PIM), PIM_per_player = sum(PIM)/n())
```


```{r}
skaters_wsib |> mutate(sib_ind = if_else(!is.na(id), 1, 0)) |>
    group_by(sib_ind) |> filter(!is.na(plus_minus)) |> filter(!is.na(PIM)) |> summarise(tot_GP = sum(GP), GP_per_player = sum(GP)/n())
```

```{r}
skaters_wsib |> mutate(sib_ind = if_else(!is.na(id), 1, 0)) |>
    group_by(sib_ind) |> filter(!is.na(plus_minus)) |> summarise(tot_pm = sum(plus_minus), pm_per_player = sum(plus_minus)/n())
```

```{r}
skaters_wsib |> mutate(sib_ind = if_else(!is.na(id), 1, 0)) |>
    group_by(sib_ind) |> filter(!is.na(shots_on_goal)) |> summarise(tot_sog = sum(shots_on_goal), sog_per_player = sum(shots_on_goal)/n())
```



```{r}
sib_comp <- skaters_wsib |> mutate(sib_ind = if_else(!is.na(id), "Sib", "No Sib")) |>
    group_by(sib_ind) |> filter(!is.na(PIM)) |> filter(!is.na(plus_minus)) |>
    summarise(size = n(),
    tot_g = sum(G), 
    tot_a = sum(A), 
    tot_pts = sum(PTS),
    tot_pm = sum(plus_minus)
    ) |>
        pivot_longer(cols = c(size, tot_g, tot_a, tot_pts, tot_pm))
```



```{r}
ggplot(data = sib_comp, aes(x = name, y = value, fill = sib_ind)) +
    geom_col(position = "dodge")
```


```{r}
sib_comp_per_player <- skaters_wsib |> mutate(sib_ind = if_else(!is.na(id), "Sib", "No Sib")) |>
    group_by(sib_ind) |> filter(!is.na(PIM)) |> filter(!is.na(plus_minus)) |> 
    summarise(GP_per_player = sum(GP)/n(),
    g_per_player = sum(G)/n(), 
    a_per_player = sum(A)/n(), 
    pts_per_player = sum(PTS)/n(),
    PIM_per_player = sum(PIM)/n(),
    pm_per_player = sum(plus_minus)/n()
    ) |>
        pivot_longer(cols = c(GP_per_player, g_per_player, a_per_player, pts_per_player, PIM_per_player, pm_per_player))
```


```{r}
ggplot(data = sib_comp_per_player, aes(x = name, y = value, fill = sib_ind)) +
    geom_col(position = "dodge")
```



```{r}
sib_comp_per_game <- skaters_wsib |> mutate(sib_ind = if_else(!is.na(id), "Sib", "No Sib")) |>
    group_by(sib_ind) |> filter(!is.na(PIM)) |> filter(!is.na(plus_minus)) |> 
    summarise(g_per_game = sum(G)/sum(GP), 
    a_per_game = sum(A)/sum(GP), 
    pts_per_game = sum(PTS)/sum(GP),
    PIM_per_game = sum(PIM)/sum(GP),
    pm_per_game = sum(plus_minus)/sum(GP)
    ) |>
        pivot_longer(cols = c(g_per_game, a_per_game, pts_per_game, PIM_per_game, pm_per_game))
```



```{r}
ggplot(data = sib_comp_per_game, aes(x = name, y = value, fill = sib_ind)) +
    geom_col(position = "dodge")
```


```{r}
skaters_wsib |> filter(!is.na(id) & id != 316 & id != 19 & id != 17 & id != 141 & id != 296) |> group_by(id, family) |> summarise(start = min(start_year), start2 = max(start_year)) |> mutate(gap = start2 - start) |> arrange(desc(gap))

skaters_wsib |> filter(id == 296)
```


```{r}
same_name <- skaters |> group_by(player) |> mutate(size = n()) |> filter(size > 1) |>
    mutate(plus_minus = if_else(!is.na(plus_minus), plus_minus, 0, 0)) |>
    summarise(G = sum(G), A = sum(A), GP = sum(GP), PTS = sum(PTS), 
    plus_minus = sum(plus_minus), PIM = sum(PIM))

```

```{r}
same_name_topg <- same_name |> arrange(desc(G)) |> slice(1:10)
```

```{r}
ggplot(data = same_name, aes(x = GP, y = G)) +
    geom_point(aes(color = G)) +
    scale_color_viridis_c() +
    geom_label(data = same_name_topg, aes(label = player))
```


```{r}
same_name_topa <- same_name |> arrange(desc(A)) |> slice(1:10)
```

```{r}
ggplot(data = same_name, aes(x = GP, y = A)) +
    geom_point(aes(color = A)) +
    scale_color_viridis_c() +
    geom_label(data = same_name_topa, aes(label = player))
```


```{r}
same_name_toppts <- same_name |> arrange(desc(PTS)) |> slice(1:10)
```

```{r}
ggplot(data = same_name, aes(x = GP, y = PTS)) +
    geom_point(aes(color = PTS)) +
    scale_color_viridis_c() +
    geom_label(data = same_name_toppts, aes(label = player))
```


```{r}
same_name_toppim <- same_name |> arrange(desc(PIM)) |> slice(1:10)
```

```{r}
ggplot(data = same_name, aes(x = GP, y = PIM)) +
    geom_point(aes(color = PIM)) +
    scale_color_viridis_c() +
    geom_label(data = same_name_toppim, aes(label = player))
```