
```{r}
library(tidyverse)
library(rvest)
library(xml2)
library(glue)
```



```{r}
url <- "https://en.wikipedia.org/wiki/List_of_family_relations_in_the_NHL"


tab <- read_html(url) |> 
  html_nodes("table")
```


```{r}
test2 <- tab[[2]] |> html_table()
test2
test3 <- tab[[3]] |> html_table()
test3
```


```{r}
siblings6 <- test2 |> separate(col = Siblings, into = c("sib1", "sib2", "sib3", "sib4", "sib5", "sib6"), sep = ",") |>
  mutate(sib2 = parse_character(sib2),
        sib3 = parse_character(sib3),
        sib4 = parse_character(sib4),
        sib5 = parse_character(sib5),
        sib6 = parse_character(sib6)) |>
  mutate(last2 = Surname,
        last3 = Surname,
        last4 = Surname,
        last5 = Surname,
        last6 = Surname,
        family = Surname) |>
  mutate(sib1 = str_remove(sib1, "\\*"), sib2 = str_remove(sib2, "\\*"),
  sib3 = str_remove(sib3, "\\*"), sib4 = str_remove(sib5, "\\*"),
  sib5 = str_remove(sib5, "\\*"), sib6 = str_remove(sib6, "\\*")) |>
  filter(!is.na(sib5)) |>
  unite("sib1", c(sib1, Surname), sep = " ") |>
  unite("sib2", c(sib2, last2), sep = " ") |>
  unite("sib3", c(sib3, last3), sep = " ") |>
  unite("sib4", c(sib4, last4), sep = " ") |>
  unite("sib5", c(sib5, last5), sep = " ") |>
  unite("sib6", c(sib6, last6), sep = " ") |>
  mutate(sib4 = "Brent Sutter", sib6 = "Ron Sutter") |>
  select(sib1, sib2, sib3, sib4, sib5, sib6, Country, family)
```

```{r}
siblings4 <- test2 |> separate(col = Siblings, into = c("sib1", "sib2", "sib3", "sib4", "sib5"), sep = ",") |>
  mutate(sib2 = parse_character(sib2),
        sib3 = parse_character(sib3),
        sib4 = parse_character(sib4)) |>
  mutate(last2 = Surname,
        last3 = Surname,
        last4 = Surname,
        family = Surname) |>
  mutate(sib1 = str_remove(sib1, "\\*"), sib2 = str_remove(sib2, "\\*"),
  sib3 = str_remove(sib3, "\\*"), sib4 = str_remove(sib4, "\\*")) |>
  filter(!is.na(sib4) & is.na(sib5)) |>
  unite("sib1", c(sib1, Surname), sep = " ") |>
  unite("sib2", c(sib2, last2), sep = " ") |>
  unite("sib3", c(sib3, last3), sep = " ") |>
  unite("sib4", c(sib4, last4), sep = " ") |>
  mutate(sib1 = if_else(sib1 == "Eric Staal",
  sib1, "Georges Boucher")) |>
  select(sib1, sib2, sib3, sib4, Country, family)

## Weird quotes around Eric Staal and Boucher brother
```

```{r}
siblings3 <- test2 |> separate(col = Siblings, into = c("sib1", "sib2", "sib3", "sib4", "sib5"), sep = ",") |>
  mutate(sib2 = parse_character(sib2),
        sib3 = parse_character(sib3),
        sib4 = parse_character(sib4)) |>
  mutate(last2 = Surname,
        last3 = Surname,
        last4 = Surname,
        family = Surname) |>
  mutate(sib1 = str_remove(sib1, "\\*"), sib2 = str_remove(sib2, "\\*"),
  sib3 = str_remove(sib3, "\\*"), sib4 = str_remove(sib4, "\\*")) |>
  filter(!is.na(sib3) & is.na(sib4)) |>
  unite("sib1", c(sib1, Surname), sep = " ") |>
  unite("sib2", c(sib2, last2), sep = " ") |>
  unite("sib3", c(sib3, last3), sep = " ") |>
  select(sib1, sib2, sib3, Country, family)
```

```{r}
siblings2 <- test2 |> separate(col = Siblings, into = c("sib1", "sib2", "sib3", "sib4", "sib5"), sep = ",") |>
  mutate(sib2 = parse_character(sib2),
        sib3 = parse_character(sib3),
        sib4 = parse_character(sib4)) |>
  mutate(last2 = Surname,
        last3 = Surname,
        last4 = Surname,
        family = Surname) |>
  mutate(sib1 = str_remove(sib1, "\\*"), sib2 = str_remove(sib2, "\\*"),
  sib3 = str_remove(sib3, "\\*"), sib4 = str_remove(sib4, "\\*")) |>
  filter(is.na(sib3)) |>
  unite("sib1", c(sib1, Surname), sep = " ") |>
  unite("sib2", c(sib2, last2), sep = " ") |>
  select(sib1, sib2, Country, family)
```

```{r}
siblings_full <- bind_rows(siblings6, siblings4, siblings3, siblings2)

siblings_full$id <- seq.int(nrow(siblings_full))
```

```{r}
siblings_full 

write.csv(siblings_full, "C://Users/gacas/NHL_Relationships/data/siblings.csv")
```


```{r}
child3 <- test3 |> 
      mutate(family_name = `Last name`,
      family_name2 = `Last name`,
      family_name3 = `Last name`,
      family_name4 = `Last name`) |>
  separate(col = Children, into = c("child1", "child2", "child3"), sep = ", ") |>
  mutate(parent = str_remove(Parent, "\\*"), 
            child1 = str_remove(child1, "\\*"),
            child2 = str_remove(child2, "\\*"),
            child3 = str_remove(child3, "\\*")) |>
            filter(!is.na(child3)) |>
            unite("parent", c(parent, family_name), sep = " ") |>
            unite("child3", c(child3, family_name2), sep = " ") |>
            unite("child2", c(child2, family_name3), sep = " ") |>
            unite("child1", c(child1, family_name4), sep = " ") 
```

```{r}
child2 <- test3 |> 
       mutate(family_name = `Last name`,
      family_name2 = `Last name`,
      family_name3 = `Last name`) |>
  separate(col = Children, into = c("child1", "child2", "child3"), sep = ", ") |>
  mutate(parent = str_remove(Parent, "\\*"), 
            child1 = str_remove(child1, "\\*"),
            child2 = str_remove(child2, "\\*"),
            child3 = str_remove(child3, "\\*")) |>
            filter(!is.na(child2) & is.na(child3)) |>
            unite("parent", c(parent, family_name), sep = " ") |>
            unite("child2", c(child2, family_name2), sep = " ") |>
            unite("child1", c(child1, family_name3), sep = " ") 
      
```

```{r}
child1 <- test3 |> 
      mutate(family_name = `Last name`,
      family_name2 = `Last name`) |>
  separate(col = Children, into = c("child1", "child2", "child3"), sep = ", ") |>
  mutate(parent = str_remove(Parent, "\\*"), 
            child1 = str_remove(child1, "\\*"),
            child2 = str_remove(child2, "\\*"),
            child3 = str_remove(child3, "\\*")) |>
            unite("parent", c(parent, family_name), sep = " ") |>
            unite("child1", c(child1, family_name2), sep = " ") |>
            filter(is.na(child2))

```

```{r}
father_son <- bind_rows(child3, child2, child1)


```


```{r}
father_son <- father_son |> mutate(family_name = `Last name`)

father_son <- father_son |> select(family_name, parent, child1, child2, child3) |> mutate(
)
```


```{r}
write.csv(father_son, "C://Users/gacas/NHL_Relationships/data/parent.csv")
```